-- Accounts are Firebase users; we store only the Firebase uid, never email or phone.
create table app_user (
    id           uuid primary key default gen_random_uuid(),
    firebase_uid varchar(128) not null unique,
    created_at   timestamptz  not null default now()
);

-- One row per question or prayer in "My Journey".
-- question / encouragement / prayer are AES-256-GCM encrypted by the application (EncryptedStringConverter).
create table journey_entry (
    id            uuid primary key,              -- generated by the app, so offline entries sync idempotently
    user_id       uuid        not null references app_user (id) on delete cascade,
    kind          varchar(16) not null check (kind in ('question', 'prayer')),
    lang          varchar(8)  not null,
    mood          varchar(32),
    themes        text[]      not null default '{}',
    verse_refs    text[]      not null default '{}',
    question      text        not null,
    encouragement text        not null,
    prayer        text        not null,
    crisis        boolean     not null default false,
    favorite      boolean     not null default false,
    created_at    timestamptz not null,
    updated_at    timestamptz not null default now()
);

create index journey_entry_user_created on journey_entry (user_id, created_at desc);
