"""Builds assets/jesus/ — the daily paintings of Jesus shown on Home.

Usage:  python tool/fetch_paintings.py

Every painting is public domain (painters who died before 1940, works before 1930),
downloaded from Wikimedia Commons. tool/paintings/sources.json is the curated list:
gentle scenes for a daily greeting (no crucifixion or burial scenes), with a focus
point so cropping keeps His face in frame. Downloads are cached in
.dart_tool/painting_cache. Commons rate-limits hard: the script is deliberately slow.
"""
import hashlib
import io
import json
import os
import time
import urllib.parse
import urllib.request

from PIL import Image

UA = {'User-Agent': 'JesusAnswersBuild/1.0 (asset build script)'}
CACHE = '.dart_tool/painting_cache'
OUT = 'assets/jesus'
MAX_WIDTH = 900


def get(url):
    for attempt in range(6):
        try:
            return urllib.request.urlopen(urllib.request.Request(url, headers=UA), timeout=60).read()
        except Exception as e:  # noqa: BLE001 — retry anything, Commons sends 429s
            print(f'  retry {attempt + 1}: {e}')
            time.sleep(15 * (attempt + 1))
    raise RuntimeError(f'could not download {url}')


def image_info(commons_title):
    q = urllib.parse.urlencode(dict(action='query', format='json', titles='File:' + commons_title,
                                    prop='imageinfo', iiprop='url|size|extmetadata', iiurlwidth=960,
                                    iiextmetadatafilter='LicenseShortName'))
    page = next(iter(json.loads(get('https://commons.wikimedia.org/w/api.php?' + q))['query']['pages'].values()))
    ii = page['imageinfo'][0]
    license_name = ii.get('extmetadata', {}).get('LicenseShortName', {}).get('value', '')
    if license_name not in ('Public domain', 'CC0'):
        raise RuntimeError(f'{commons_title}: license is {license_name!r}, expected public domain')
    # 960 is a standard Commons thumbnail width; smaller originals are used as-is.
    return (ii['thumburl'] if ii['width'] > 960 else ii['url']), ii['descriptionurl'], license_name


def main():
    os.makedirs(CACHE, exist_ok=True)
    os.makedirs(OUT, exist_ok=True)
    sources = json.load(open('tool/paintings/sources.json', encoding='utf-8'))['paintings']
    manifest = []
    for n, src in enumerate(sources, 1):
        print(f'▸ {n:02d} {src["title"]}')
        cached = os.path.join(CACHE, hashlib.sha1(src['commons'].encode()).hexdigest() + '.img')
        url, page, license_name = image_info(src['commons'])
        if not os.path.exists(cached):
            data = get(url)
            open(cached, 'wb').write(data)
            time.sleep(8)
        im = Image.open(cached).convert('RGB')
        if im.width > MAX_WIDTH:
            im = im.resize((MAX_WIDTH, round(im.height * MAX_WIDTH / im.width)), Image.LANCZOS)
        buf = io.BytesIO()
        im.save(buf, 'JPEG', quality=82, optimize=True, progressive=True)
        file = f'{n:02d}.jpg'
        open(os.path.join(OUT, file), 'wb').write(buf.getvalue())
        manifest.append({
            'file': file,
            'title': src['title'],
            'artist': src['artist'],
            'year': src.get('year'),
            'focusX': src.get('focusX', 0),
            'focusY': src.get('focusY', -0.4),
            'license': license_name,
            'source': page,
        })
        time.sleep(2)
    json.dump({'_comment': 'Generated by tool/fetch_paintings.py — edit tool/paintings/sources.json instead.',
               'paintings': manifest},
              open(os.path.join(OUT, 'paintings.json'), 'w', encoding='utf-8'), indent=1, ensure_ascii=False)
    total = sum(os.path.getsize(os.path.join(OUT, m['file'])) for m in manifest)
    print(f'✓ {len(manifest)} paintings, {total / 1e6:.1f} MB')


if __name__ == '__main__':
    main()
